In [39]:
import pandas as pd
import numpy as np

In [41]:
dfs_p = {}
dfs_n = {}

for ptable in np.arange(0.05, 0.46, 0.05):
    ptable = round(ptable, 2)

    df_p = pd.read_table(
        f"../ld_positive_{ptable}.txt",
        delimiter=r"\s+"
    )

    df_n = pd.read_table(
        f"../ld_negative_{ptable}.txt",
        delimiter=r"\s+"
    )


    df_p['Ex'] = df_p['Ex'] - ptable
    df_n['Ex'] = df_n['Ex']- ptable

    if ptable >= 0.25:
        df_p = df_p[df_p['Ex'] >= 0]
        df_n = df_n[df_n['Ex'] >= 0]
    
    dfs_p[ptable] = df_p
    dfs_n[ptable] = df_n

In [53]:
df_all_p = pd.concat(dfs_p.values(), ignore_index=True)

df_all_p["Ex"] = df_all_p["Ex"].round(2)
df_all_p = (
    df_all_p
    .sort_values(by="Ex", ascending=True)
    .reset_index(drop=True)
)

df_all_p = df_all_p.drop_duplicates(subset="Ex", keep="first")

df_all_p.to_pickle("master_base_ld_p.pkl")

In [55]:
df_all_n = pd.concat(dfs_n.values(), ignore_index=True)


df_all_n["Ex"] = df_all_n["Ex"].round(2)
df_all_n = (
    df_all_n
    .sort_values(by="Ex", ascending=True)
    .reset_index(drop=True)
)

df_all_n = df_all_n.drop_duplicates(subset="Ex", keep="first")

df_all_n.to_pickle("master_base_ld_n.pkl")

In [57]:
df_test1 = pd.read_pickle("master_base_ld_p.pkl")

df_test1.head()

,Ex,total,JP=0.0,JP=1.0,JP=2.0,JP=3.0,JP=4.0,JP=5.0,JP=6.0,JP=7.0,JP=8.0
0,0.00,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30
1,0.05,4.860000e-01,2.000000e-01,1.000000e-30,9.560000e-02,1.000000e-30,9.560000e-02,1.000000e-30,9.560000e-02,1.000000e-30,1.000000e-30
3,0.10,9.720000e-01,4.000000e-01,1.000000e-30,1.912000e-01,1.000000e-30,1.912000e-01,1.000000e-30,1.912000e-01,1.000000e-30,1.000000e-30
5,0.15,1.458000e+00,6.000000e-01,1.000000e-30,2.868000e-01,1.000000e-30,2.868000e-01,1.000000e-30,2.868000e-01,1.000000e-30,1.000000e-30
7,0.20,1.944000e+00,8.000000e-01,1.000000e-30,3.824000e-01,1.000000e-30,3.824000e-01,1.000000e-30,3.824000e-01,1.000000e-30,1.000000e-30

In [61]:
df_test2 = pd.read_pickle("master_base_ld_n.pkl")

df_test2.head()

,Ex,total,JP=0.0,JP=1.0,JP=2.0,JP=3.0,JP=4.0,JP=5.0,JP=6.0,JP=7.0,JP=8.0
0,0.00,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30
1,0.05,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30
3,0.10,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30
5,0.15,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30
7,0.20,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30,1.000000e-30

In [51]:
print(df_all_n.loc[3:4, "Ex"].map(lambda x: f"{x:.17f}"))

3    0.09999999999999998
4    0.10000000000000001
Name: Ex, dtype: object